# Generated by Django 5.0.1 on 2024-03-26 01:02

import django.core.files.storage
import django.db.models.deletion
import pathlib
import zap.apps.chat.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('filespro', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('chat_file', models.FileField(blank=True, storage=django.core.files.storage.FileSystemStorage(location=pathlib.PurePosixPath('/usr/src/priv_files/chat_files')), upload_to=zap.apps.chat.models.upload_to_path)),
                ('filespro_folder', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='filespro.filesprofolder')),
            ],
        ),
        migrations.CreateModel(
            name='Usership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_host', models.BooleanField(default=False, verbose_name='is_host')),
                ('chat_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chat.chatsession')),
            ],
        ),
    ]
