version: '3'
services:
  web:
    container_name: web_zap
    build: ./dja/
    command: python manage.py init-db #tail -f /dev/null
    env_file:
      - .env
    volumes:
      - ./dja/:/usr/src/app/
      - ./media:/usr/src/media
      - ./priv_files:/usr/src/priv_files
      - ./cstatic:/usr/src/cstatic
    depends_on:
      - pgdb

  pgdb:
    image: postgres # port 5432
    restart: always
    volumes:
      - ./pgdb/pgdb:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=${POSTGRESQL_NAME}
      - POSTGRES_USER=${POSTGRESQL_USER}
      - POSTGRES_PASSWORD=${POSTGRESQL_PASSWORD}
    ports:
      - 5432:5432
