# Generated by Django 5.0.1 on 2024-02-11 22:03

import django.core.files.storage
import django.db.models.deletion
import pathlib
import zap.apps.filespro.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUploadUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('max_storage_size', models.PositiveIntegerField(default=0)),
                ('remaining_storage', models.PositiveIntegerField(default=0)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
        migrations.CreateModel(
            name='FileUploadFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(storage=django.core.files.storage.FileSystemStorage(base_url='/media_private', location=pathlib.PurePosixPath('/usr/src/priv_files')), upload_to=zap.apps.filespro.models.uploadPathFunction)),
                ('file_name', models.CharField(max_length=50)),
                ('file_size', models.PositiveIntegerField()),
                ('file_upload_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='filespro.fileuploaduser')),
            ],
        ),
        migrations.AddIndex(
            model_name='fileuploaduser',
            index=models.Index(fields=['content_type', 'object_id'], name='filespro_fi_content_24b9b8_idx'),
        ),
    ]
