# Generated by Django 5.0.1 on 2024-02-04 03:49

import django.db.models.deletion
import zap.apps.wsi.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_object_id', models.PositiveIntegerField()),
                ('file', models.FileField(blank=True, null=True, upload_to=zap.apps.wsi.models.uploadPathFunction)),
                ('file_name', models.CharField(max_length=50)),
                ('owner_content_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
        ),
    ]
