from django.contrib.sitemaps import Sitemap
from django.urls import reverse

from .models import Post


class PostSitemap(Sitemap):
    i18n = True

    def items(self):
        return Post.objects.all()

    def lastmod(self, post):
        return post.pub_date


class RootSitemap(Sitemap):
    i18n = True
    ### Generate sitemap for pages not generated by DB
    priority = 0.6

    def items(self):
        ### URL path names to include in sitemap
        return [
            "filespro:download_file",
            "users:signin_0",
        ]

    def location(self, url_name):
        ### Reverse location of URL paths
        return reverse(url_name)


# ######### Sites / sitemap  init
# ### Change the site manually in the Admin (best) or do the following:
# ###  once, AFTER migrate.
# ### This sets the Site parameters when Django loads
# ### the sitemap.xml have this domain url in all the links
# ### comment this section before migrate
# from django.contrib.sites.models import Site

# mysite = Site.objects.get_current()
# mysite.domain = "zap.com"
# mysite.name = "Zap"
# mysite.save()
